# Generated by Django 5.0.1 on 2024-01-08 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoTraduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "TipoTraduccion",
                "verbose_name_plural": "TiposTraducciones",
                "db_table": "tipotraduccion",
            },
        ),
        migrations.CreateModel(
            name="Traduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("texto_traducido", models.TextField()),
                ("estado", models.BooleanField(default=True)),
                (
                    "pronunciacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tipo_traduccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="traductor.tipotraduccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Traduccion",
                "verbose_name_plural": "Traducciones",
                "db_table": "traduccion",
            },
        ),
    ]
